apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/app

patchesStrategicMerge:
  - patches/generated-image-patch.yml

namePrefix: simple-sample-
commonLabels:
  app: simple-sample