apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
      - name: app
        image: 935491670310.dkr.ecr.eu-central-1.amazonaws.com/fedex-gitops:e40155db